spring:
  profiles:
    default: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: pjsassy0401@gmail.com
    password: tppevixnakaifyml
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/sassy
    username: sa
    password: 1
    driver-class-name: org.h2.Driver


  redis:
    host: 127.0.0.1
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  secret: 7xc6zv7867sdva7fywefe78sdyf78asyf78aseyf78ysdf8xy8v7yv78ayvd87dfyvadfbdybgWEJF32HJRK3H3JK2KJ;

logging.level:
  org.hibernate.SQL: debug